# Generated by Django 5.1 on 2024-08-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Названия фильма')),
                ('short_description', models.CharField(max_length=250, verbose_name='Описание фильма')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
